[build]
# target-dir = "target"

# [patch.crates-io]
# zstd = { git = "https://github.com/gyscos/zstd-rs.git", features = ["wasm"] }

[patch.'https://github.com/tvmlabs/tvm-sdk.git']
# tvm_block = { git = 'https://github.com/awnion/tvm-sdk.git', branch = 'feature/parallel_send' }
# tvm_block_json = { git = 'https://github.com/awnion/tvm-sdk.git', branch = 'feature/parallel_send' }
# tvm_executor = { git = 'https://github.com/awnion/tvm-sdk.git', branch = 'feature/parallel_send', features = ['signature_with_id'] }
# tvm_types = { git = 'https://github.com/awnion/tvm-sdk.git', branch = 'feature/parallel_send' }
# tvm_vm = { git = 'https://github.com/awnion/tvm-sdk.git', branch = 'feature/parallel_send', features = ['gosh'] }

# tvm_block = { path = "/Users/aw/pro/tvmlabs/tvm-sdk/tvm_block" }
# tvm_block_json = { path = "/Users/aw/pro/tvmlabs/tvm-sdk/tvm_block_json" }
# tvm_executor = { path = "/Users/aw/pro/tvmlabs/tvm-sdk/tvm_executor", features = [
#     'signature_with_id',
# ] }
# tvm_types = { path = "/Users/aw/pro/tvmlabs/tvm-sdk/tvm_types" }
# tvm_vm = { path = "/Users/aw/pro/tvmlabs/tvm-sdk/tvm_vm", features = ['gosh'] }
