name: acki nacki lib-web publish

on:
  release:
    types: [published]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    if: endsWith(github.ref, 'an.libweb')
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '16.x'
          registry-url: https://registry.npmjs.org/

      - name: Lib-web
        run: npm publish --access public
        working-directory: ./packages/lib-web
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

